### ISSUE TITLE
import themeStore, { setTheme } from 'svelte-themes';

### ISSUE THREAD

**Issue by HBartolin** [beynar/svelte-themes#7]
Why I get error:

import themeStore, { setTheme } from 'svelte-themes';

`[plugin:vite:import-analysis] Failed to resolve entry for package "svelte-themes". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "svelte-themes" package
C:/dev/code-ws/EtlevsDrowTSv2Firebase/src/routes/privatedashboard/+page.svelte
    at packageEntryFailure (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23377:9)
    at tryNodeResolve (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Context.resolveId (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.resolveId (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
    at async TransformContext.resolve (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
    at async normalizeUrl (file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40500:34)
    at async file:///C:/dev/code-ws/EtlevsDrowTSv2Firebase/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.`

**Comment by telmogoncalves** [comment]
```
import themeStore, { setTheme } from 'svelte-themes/themeStore'
```
